# latexmk configuration for rigorous compilation
# Treats warnings as errors

$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$pdf_mode = 1;
$postscript_mode = 0;
$dvi_mode = 0;

# Clean up auxiliary files
@generated_exts = qw(aux log out toc nav snm vrb bbl blg);

# Treat any warnings as fatal errors
$warnings_as_errors = 1;
