"""
Utilities for loading structured MINIX analysis data generated by the pipeline.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict


DATA_FILES = {
    "kernel_structure": "kernel_structure.json",
    "process_table": "process_table.json",
    "memory_layout": "memory_layout.json",
    "ipc_system": "ipc_system.json",
    "boot_sequence": "boot_sequence.json",
    "statistics": "statistics.json",
}


@dataclass
class MinixDataLoader:
    """
    Lazy-loading accessor for pipeline data residing in diagrams/data/.
    """

    data_dir: Path = Path("diagrams/data")

    def __post_init__(self) -> None:
        self.data_dir = self.data_dir.resolve()
        if not self.data_dir.exists():
            raise FileNotFoundError(
                f"Data directory not found: {self.data_dir}. "
                "Run `make pipeline` to generate analysis artifacts."
            )
        self._cache: Dict[str, Dict[str, Any]] = {}

    def load(self, key: str) -> Dict[str, Any]:
        """Load and cache the JSON payload corresponding to the given key."""
        if key not in DATA_FILES:
            raise KeyError(f"Unknown dataset key: {key}")

        if key not in self._cache:
            path = self.data_dir / DATA_FILES[key]
            if not path.exists():
                raise FileNotFoundError(
                    f"Dataset missing: {path}. "
                    "Ensure `make pipeline` has been executed recently."
                )
            with path.open("r", encoding="utf-8") as handle:
                self._cache[key] = json.load(handle)

        return self._cache[key]

    @property
    def kernel_structure(self) -> Dict[str, Any]:
        return self.load("kernel_structure")

    @property
    def process_table(self) -> Dict[str, Any]:
        return self.load("process_table")

    @property
    def memory_layout(self) -> Dict[str, Any]:
        return self.load("memory_layout")

    @property
    def ipc_system(self) -> Dict[str, Any]:
        return self.load("ipc_system")

    @property
    def boot_sequence(self) -> Dict[str, Any]:
        return self.load("boot_sequence")

    @property
    def statistics(self) -> Dict[str, Any]:
        return self.load("statistics")
